name: CICD
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run unit test
        run: |
          cd Test2/app
          python3 -m unittest test_app.py

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to ec2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "Test2/app"
          SCRIPT_AFTER: |
            cd app
            nohup python3 app.py > app.log 2>&1 &
