name: CICD
on:
  push:
    branches:
      - main
    paths:
      - Test2/app/**
      - .github/workflows/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd Test2/app
          npm install

      - name: Run unit test
        run: |
          cd Test2/app
          npm test
