name: CICD
on:
  push:
    branches:
      - main
    paths:
      - Test2/app/**
      - .github/workflows/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd Test2/app
          pip3 install -r requirements.txt

      - name: Run unit test
        run: |
          cd Test2/app
          python3 -m unittest test_app.py

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to ec2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "Test2/app"
          SCRIPT_AFTER: |
            ls -la
            pip3 install -r requirements.txt
            python3 app.py
